Guide to developing homebrew for repro carts
gbadev-org/gbadoc pull request #16
Opened 2022-06-25 14:30 UTC by velipso

There have been discussions/questions on discord around how bootleg carts work, and how to save on them.  This is intended to be a guide for homebrew developers.  More could definitely be added to it, but I think it's a good starting point.

2022-06-25 22:29 UTC, avivace requested changes
I really like this! Thanks @velipso . My only concern is the mentioning / direct pointers and screenshots of Aliexpress..

2022-06-27 08:03 UTC, avivace approved these changes
Looks great to me, thanks!

2022-06-28 12:23 UTC, exelotl approved these changes
It all looks good to me! I've left some comments, but can always be addressed in a future PR.

2022-06-28 12:23 UTC, exelotl commented on content/bootleg-carts/introduction.md
> +__asm("nop");
Is it possible to use `WAITCNT` + ROM mirrors to eliminate the need for `nop`? If so, it might be worth mentioning and/or demonstrating what settings to use.

2022-06-28 12:23 UTC, exelotl commented on content/bootleg-carts/introduction.md
> +**IMPORTANT NOTE:** Since we need to control the reads/writes sent to the ROM, we cannot run the
I still don't understand the technical reason for this, is it just the nature of flash chips that they can't be read from while they are handling commands? Is there a way to reword this to make the _why_ more clear for dummies like me?

2022-06-28 12:38 UTC, velipso commented on content/bootleg-carts/introduction.md
> +__asm("nop");
That's a good question, I don't know.  I haven't tested that.

2022-06-28 12:39 UTC, velipso commented on content/bootleg-carts/introduction.md
> +**IMPORTANT NOTE:** Since we need to control the reads/writes sent to the ROM, we cannot run the
Some operations on the flash chips (CFI and Auto-Select are two that come to mind) actually change the read behavior of the chip.  You don't want the CPU reading special values from the ROM while trying to execute.

2022-06-28 12:40 UTC, velipso commented on content/bootleg-carts/introduction.md
> +TODO: write more information about CFI and sector layout.
Yeah, I'm happy to add more when I get it figured out myself, or someone else can too.  Goombacolor doesn't solve this issue in a general way, so I couldn't link to it in this case.

2022-07-04 03:02 UTC, velipso commented
I think we're good to merge this for now..?  I know it isn't perfect but I think it's a good start and I can add to it over time, if that's okay.

2022-07-04 07:30 UTC, avivace commented on content/bootleg-carts/introduction.md
> +TODO: write more information about CFI and sector layout.
Maybe we can open an issue about this?

2022-07-04 07:31 UTC, merged