Add explanation of converting between floating  and fixed point
gbadev-org/gbadoc pull request #21
Opened 2024-03-20 22:51 UTC by AntonioND

This is useful in many situations, like when generating fixed point
constants, or when printing fixed point values for debugging (or non
debugging) purposes.

Also, fix some qualifiers (`extern` isn't needed, `const` is nice to
use).

2024-03-22 22:47 UTC, avivace approved these changes

2024-03-23 11:00 UTC, avivace requested changes

2024-03-23 11:00 UTC, avivace commented on content/fixed-point-math.md
> +Remember that the operations are floating point operations, so they will be slow. There is an exception. If you use `constexpr` or if the compiler detects that an expression is constant, it will calc
```suggestion
Remember that those are floating point operations, so they will be slow. There is an exception: if you use `constexpr` or if the compiler detects that an expression is constant, it will calculate it at compile time automatically. This is very useful for setting initial fixed point values from floating point values.
```

2024-03-23 13:30 UTC, AntonioND commented on content/fixed-point-math.md
> +int player_speed = (1 << player_fp) + ((5 << player_fp) / 8);
This is correct: ``1 << 3`` is 8, so the first part of the addition is correct. The second one is just ``5 * 8 / 8``, but at least this way it's more clear that the intention is to have 5/8 in fixed point, rather than just a random 5.

2024-03-23 13:32 UTC, AntonioND commented on content/fixed-point-math.md
> +Okay, so now you have a way to do mathematical operations efficiently. How do you set the initial values in a convenient way? How do you print the values in a way that is easier to understand than ve
I think the "now" should stay, I've made the change myself.

2024-03-23 13:33 UTC, AntonioND commented on content/fixed-point-math.md
> +int player_speed = (1 << player_fp) + ((5 << player_fp) / 8);
Or maybe I've misunderstood your suggestion.

2024-03-24 00:31 UTC, avivace commented on content/fixed-point-math.md
> +int player_speed = (1 << player_fp) + ((5 << player_fp) / 8);
Yeah I wasn't discussing the correctness, just to expand a bit more explaining the shift

2024-03-24 02:21 UTC, AntonioND commented on content/fixed-point-math.md
> +int player_speed = (1 << player_fp) + ((5 << player_fp) / 8);
I see what you mean, but I'm not sure how to change the explanation to make it more clear. I think that the shift itself doesn't need to be understood as a multiplication, more like "making room for decimals".

In any case, if the rest of the PR is ok, we can merge it and that can be improved later, all I wanted with this change is explain a bit better where "5" was coming from, and now it's just using the general formula for any number, so...

2024-03-24 17:48 UTC, avivace approved these changes

2024-03-24 17:49 UTC, merged